import type { WorkflowTemplate } from "../types";
export const BUSINESS_TEMPLATES: Partial<WorkflowTemplate>[] = [
    {
        id: "notion-page-fetch-to-slack-lite",
        name: "Notion Page Fetch to Slack Lite",
        description: "Read recent entries from Notion and publish a short summary to Slack.",
        category: "business",
        difficulty: "beginner",
        estimatedSetupMinutes: 5,
        tags: ["manual", "notion", "transform", "slack"],
        availableTriggerId: "manual",
        highlights: ["Notion read", "Slack distribution"],
        requiredCredentials: ["notion", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "notion", nodeIds: ["np-notion"], description: "Notion credential for database reads" },
            { platform: "slack", nodeIds: ["np-slack"], description: "Slack credential for updates" },
        ],
        fieldRequirements: [
            {
                nodeId: "np-notion",
                field: "databaseId",
                label: "Notion Database ID",
                placeholder: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                type: "text",
                required: true,
            },
            {
                nodeId: "np-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "np-manual",
                type: "manualTrigger",
                position: { x: 80, y: 220 },
                data: {
                    label: "Manual Trigger",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "np-notion",
                type: "notionNode",
                position: { x: 320, y: 220 },
                data: {
                    label: "Read Notion Items",
                    nodeType: "notionNode",
                    isConfigured: false,
                    responseName: "notionItems",
                    credentialId: "",
                    operation: "get_many",
                    databaseId: "",
                    pageSize: 5,
                },
            },
            {
                id: "np-transform",
                type: "transformNode",
                position: { x: 560, y: 220 },
                data: {
                    label: "Build Summary",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "npSummary",
                    expression: '{"message":"Fetched recent Notion entries at {np-manual.triggeredAt}"}',
                },
            },
            {
                id: "np-slack",
                type: "slackNode",
                position: { x: 800, y: 160 },
                data: {
                    label: "Post to Slack",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "npSlack",
                    credentialId: "",
                    channel: "",
                    message: "{npSummary.data.message}",
                },
            },
            {
                id: "np-log",
                type: "logNode",
                position: { x: 800, y: 280 },
                data: {
                    label: "Log",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "Notion to Slack sync finished",
                },
            },
        ],
        edges: [
            { id: "e1", source: "np-manual", target: "np-notion" },
            { id: "e2", source: "np-notion", target: "np-transform" },
            { id: "e3", source: "np-transform", target: "np-slack" },
            { id: "e4", source: "np-slack", target: "np-log" },
        ],
    },
    {
        id: "notion-backlog-priority-sync",
        name: "Notion Backlog Priority Sync",
        description: "Score backlog items with OpenAI and route high-priority work into GitHub.",
        category: "business",
        difficulty: "intermediate",
        estimatedSetupMinutes: 11,
        tags: ["cron", "transform", "openai", "condition", "github", "slack"],
        availableTriggerId: "manual",
        highlights: ["Backlog context generation", "AI priority scoring", "GitHub issue handoff"],
        requiredCredentials: ["openai", "github", "slack"],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "openai", nodeIds: ["nb-openai"], description: "OpenAI credential for scoring" },
            { platform: "github", nodeIds: ["nb-github"], description: "GitHub credential for issue creation" },
            { platform: "slack", nodeIds: ["nb-slack"], description: "Slack credential for notifications" },
        ],
        fieldRequirements: [
            {
                nodeId: "nb-openai",
                field: "model",
                label: "OpenAI Model",
                placeholder: "gpt-5-mini",
                type: "select",
                required: true,
                options: [
                    { value: "gpt-5-mini", label: "GPT-5 Mini (Recommended)" },
                    { value: "gpt-5", label: "GPT-5" },
                    { value: "gpt-4.1-mini", label: "GPT-4.1 Mini" },
                ],
                defaultValue: "gpt-5-mini",
            },
            {
                nodeId: "nb-github",
                field: "owner",
                label: "GitHub Owner",
                placeholder: "your-org",
                type: "text",
                required: true,
            },
            {
                nodeId: "nb-github",
                field: "repo",
                label: "GitHub Repository",
                placeholder: "product-backlog",
                type: "text",
                required: true,
            },
            {
                nodeId: "nb-slack",
                field: "channel",
                label: "Slack Channel",
                placeholder: "Optional - webhook default channel",
                type: "text",
                required: false,
            },
        ],
        nodes: [
            {
                id: "nb-cron",
                type: "cronTrigger",
                position: { x: 80, y: 260 },
                data: {
                    label: "Daily Backlog Sync",
                    nodeType: "cronTrigger",
                    isConfigured: true,
                    schedule: "daily",
                    hour: 9,
                    minute: 0,
                    timezone: "UTC",
                },
            },
            {
                id: "nb-notion",
                type: "transformNode",
                position: { x: 320, y: 260 },
                data: {
                    label: "Build Backlog Context",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "nbBacklog",
                    expression: '{"items":[{"title":"Fix onboarding edge cases","impact":"high"},{"title":"Improve analytics dashboard","impact":"medium"}],"generatedAt":"{nb-cron.triggeredAt}"}',
                },
            },
            {
                id: "nb-openai",
                type: "openaiNode",
                position: { x: 560, y: 260 },
                data: {
                    label: "Score Priority",
                    nodeType: "openaiNode",
                    isConfigured: false,
                    responseName: "nbScore",
                    credentialId: "",
                    model: "",
                    systemPrompt: "Classify urgency as high or normal.",
                    prompt: "Backlog data: {json nbBacklog}. Return high or normal only.",
                    temperature: 0,
                },
            },
            {
                id: "nb-transform",
                type: "transformNode",
                position: { x: 800, y: 260 },
                data: {
                    label: "Build Issue Payload",
                    nodeType: "transformNode",
                    isConfigured: true,
                    responseName: "nbPayload",
                    expression: '{"title":"Backlog follow-up","backlog":{json nbBacklog}}',
                },
            },
            {
                id: "nb-condition",
                type: "conditionNode",
                position: { x: 1040, y: 260 },
                data: {
                    label: "Route Priority",
                    nodeType: "conditionNode",
                    isConfigured: true,
                    expression: "{nbScore.data}",
                    routes: ["high", "normal"],
                    defaultRoute: "normal",
                    rulesJson: '[{"route":"high","operator":"contains","value":"high"}]',
                    responseName: "nbRoute",
                },
            },
            {
                id: "nb-github",
                type: "githubNode",
                position: { x: 1280, y: 200 },
                data: {
                    label: "Create GitHub Issue",
                    nodeType: "githubNode",
                    isConfigured: false,
                    responseName: "nbIssue",
                    credentialId: "",
                    operation: "create_issue",
                    owner: "",
                    repo: "",
                    title: "{nbPayload.data.title}",
                    body: "Generated from backlog sync: {json nbPayload.data.backlog}",
                    labelsTemplate: '["backlog","auto"]',
                },
            },
            {
                id: "nb-slack",
                type: "slackNode",
                position: { x: 1280, y: 320 },
                data: {
                    label: "Post Normal Update",
                    nodeType: "slackNode",
                    isConfigured: false,
                    responseName: "nbSlack",
                    credentialId: "",
                    channel: "",
                    message: "Backlog routing outcome: {nbRoute.route}. Priority signal: {nbScore.data}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "nb-cron", target: "nb-notion" },
            { id: "e2", source: "nb-notion", target: "nb-openai" },
            { id: "e3", source: "nb-openai", target: "nb-transform" },
            { id: "e4", source: "nb-transform", target: "nb-condition" },
            { id: "e5", source: "nb-condition", sourceHandle: "high", target: "nb-github" },
            { id: "e6", source: "nb-condition", sourceHandle: "normal", target: "nb-slack" },
        ],
    },
    {
        id: "mpesa-payment-whatsapp-receipt",
        name: "M-Pesa Payment → WhatsApp Receipt",
        description: "Trigger manually (or via webhook) with payment details, log it, and send a branded WhatsApp receipt to the customer instantly.",
        category: "business",
        difficulty: "beginner",
        estimatedSetupMinutes: 8,
        tags: ["manual", "mpesa", "whatsapp", "log", "receipt", "kenya"],
        availableTriggerId: "manual",
        highlights: ["M-Pesa STK Push", "Instant WhatsApp receipt", "Audit log"],
        requiredCredentials: [],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "mpesa" as never, nodeIds: ["mp-mpesa"], description: "M-Pesa Daraja API credential (Consumer Key, Consumer Secret, Shortcode, Passkey)" },
            { platform: "whatsapp" as never, nodeIds: ["mp-whatsapp"], description: "WhatsApp Business API credential (Access Token, Phone Number ID)" },
        ],
        fieldRequirements: [
            {
                nodeId: "mp-mpesa",
                field: "phoneNumber",
                label: "Customer Phone Number",
                placeholder: "0712345678",
                type: "text",
                required: true,
            },
            {
                nodeId: "mp-mpesa",
                field: "amount",
                label: "Amount (KES)",
                placeholder: "500",
                type: "text",
                required: true,
            },
            {
                nodeId: "mp-whatsapp",
                field: "to",
                label: "WhatsApp Recipient Phone",
                placeholder: "254712345678",
                type: "text",
                required: true,
            },
        ],
        nodes: [
            {
                id: "mp-trigger",
                type: "manualTrigger",
                position: { x: 80, y: 260 },
                data: {
                    label: "New Payment",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "mp-mpesa",
                type: "mpesaNode",
                position: { x: 320, y: 260 },
                data: {
                    label: "Send STK Push",
                    nodeType: "mpesaNode",
                    isConfigured: false,
                    responseName: "mpesaResult",
                    credentialId: "",
                    operation: "stk_push",
                    phoneNumber: "",
                    amount: "",
                    accountReference: "Fynt Order",
                    transactionDesc: "Payment for services",
                },
            },
            {
                id: "mp-log",
                type: "logNode",
                position: { x: 560, y: 260 },
                data: {
                    label: "Log Payment",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "M-Pesa STK push sent. CheckoutRequestID: {mpesaResult.checkoutRequestId}",
                },
            },
            {
                id: "mp-whatsapp",
                type: "whatsappNode",
                position: { x: 800, y: 260 },
                data: {
                    label: "Send WhatsApp Receipt",
                    nodeType: "whatsappNode",
                    isConfigured: false,
                    responseName: "waReceipt",
                    credentialId: "",
                    messageType: "text",
                    to: "",
                    message: "✅ Hi! Your M-Pesa payment request of KES {mp-mpesa.amount} has been sent to your phone. Please enter your M-Pesa PIN to complete. Ref: {mpesaResult.checkoutRequestId}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "mp-trigger", target: "mp-mpesa" },
            { id: "e2", source: "mp-mpesa", target: "mp-log" },
            { id: "e3", source: "mp-log", target: "mp-whatsapp" },
        ],
    },
    {
        id: "africastalking-bulk-sms-broadcast",
        name: "Bulk SMS Broadcast via Africa's Talking",
        description: "Send a promotional or alert SMS to a list of Kenyan phone numbers on a schedule or manually.",
        category: "business",
        difficulty: "beginner",
        estimatedSetupMinutes: 5,
        tags: ["manual", "africastalking", "sms", "broadcast", "kenya"],
        availableTriggerId: "manual",
        highlights: ["Bulk SMS to any number list", "Africa's Talking integration", "Cost-effective outreach"],
        requiredCredentials: [],
        setupMode: "credential_only",
        templateVersion: 1,
        requiredBindings: [
            { platform: "africastalking" as never, nodeIds: ["at-sms"], description: "Africa's Talking credential (API Key, Username)" },
        ],
        fieldRequirements: [
            {
                nodeId: "at-sms",
                field: "to",
                label: "Recipients (comma-separated)",
                placeholder: "+254712345678,+254723456789",
                type: "text",
                required: true,
            },
            {
                nodeId: "at-sms",
                field: "message",
                label: "SMS Message",
                placeholder: "Hello! Here is today's update...",
                type: "text",
                required: true,
            },
        ],
        nodes: [
            {
                id: "at-trigger",
                type: "manualTrigger",
                position: { x: 80, y: 260 },
                data: {
                    label: "Start Broadcast",
                    nodeType: "manualTrigger",
                    isConfigured: true,
                },
            },
            {
                id: "at-sms",
                type: "africastalkingNode",
                position: { x: 320, y: 260 },
                data: {
                    label: "Send SMS",
                    nodeType: "africastalkingNode",
                    isConfigured: false,
                    responseName: "smsResult",
                    credentialId: "",
                    operation: "send_sms",
                    to: "",
                    message: "",
                },
            },
            {
                id: "at-log",
                type: "logNode",
                position: { x: 560, y: 260 },
                data: {
                    label: "Log Result",
                    nodeType: "logNode",
                    isConfigured: true,
                    level: "info",
                    message: "SMS broadcast complete. Sent: {smsResult.sentCount} / {smsResult.totalRecipients}",
                },
            },
        ],
        edges: [
            { id: "e1", source: "at-trigger", target: "at-sms" },
            { id: "e2", source: "at-sms", target: "at-log" },
        ],
    },
];

