import { AINode, AnthropicNode, ConditionNode, CronTriggerNode, DelayNode, DiscordNode, FilterNode, GeminiNode, GitHubNode, HTTPNode, LogNode, NotionNode, OpenAINode, SlackNode, TransformNode, TriggerNode, WebhookTriggerNode, MpesaNode, KraEtrNode, WhatsAppNode, EmailNode } from '@/components/workflows/nodes';
export const nodeTypes = {
    aiNode: AINode,
    triggerNode: TriggerNode,
    httpTrigger: HTTPNode,
    githubNode: GitHubNode,
    notionNode: NotionNode,
    openaiNode: OpenAINode,
    geminiNode: GeminiNode,
    anthropicNode: AnthropicNode,
    slackNode: SlackNode,
    discordNode: DiscordNode,
    manualTrigger: TriggerNode,
    webhookTrigger: WebhookTriggerNode,
    cronTrigger: CronTriggerNode,
    conditionNode: ConditionNode,
    delayNode: DelayNode,
    logNode: LogNode,
    transformNode: TransformNode,
    filterNode: FilterNode,
    mpesaNode: MpesaNode,
    whatsappNode: WhatsAppNode,
    kraEtrNode: KraEtrNode,
    emailNode: EmailNode,
} as const;
export type NodeType = keyof typeof nodeTypes;
